# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Delivery:
  fields:
    list: delivery_date, bags, recipient_id, team_id
    form: delivery_date, comment, bags, recipient_id, team_id
  order_by: 
  relationships: 
  filters: 
  search: 
  application: ssvp

Recipient:
  fields:
    list: first_name, last_name, address, city, postal_code, phone_number, adults, children
    form: first_name, last_name, address, city, postal_code, phone_number, adults, children, notes, delivery_notes
  order_by: 
  relationships: 
  filters: 
  search: 
  application: ssvp

Vincentian:
  fields:
    list: first_name, last_name, address, city, postal_code, phone_number, team
    form: first_name, last_name, address, city, postal_code, phone_number, team, notes
  order_by: 
  relationships: 
  filters: 
  search: 
  application: ssvp

